Add tests for DeleteDeadlineCommand & related classes
AY2021S2-CS2103T-T11-2/tp pull request #167
Opened 2021-03-24 18:19 UTC by vevek

Closes #165

2021-03-24 18:19 UTC, vevek commented
Ready for review! Thanks!

2021-03-25 08:21 UTC, samuelfangjw requested changes
just the typo there, the rest seems ok.

2021-03-25 08:21 UTC, samuelfangjw commented on src/test/java/seedu/address/logic/commands/DeleteDeadlineCommandTest.java
> +                model.getFilteredProjectList().get(INDEX_FIRST.getZeroBased()).getDeadlines().getDeadlines().size());
Demeter's law! Probably find for now since we did similar things in other areas, but I think we should file an issue and 1 shot change all.

2021-03-25 08:21 UTC, samuelfangjw commented on src/test/java/seedu/address/logic/commands/DeleteDeadlineCommandTest.java
> +        // different person -> returns false
different deadline here

2021-03-25 08:25 UTC, vevek commented on src/test/java/seedu/address/logic/commands/DeleteDeadlineCommandTest.java
> +        // different person -> returns false
Nice thanks!

2021-03-25 08:42 UTC, samuelfangjw approved these changes

2021-03-25 08:42 UTC, merged