Add tests for DeleteEventCommand & related classes
AY2021S2-CS2103T-T11-2/tp pull request #170
Opened 2021-03-24 18:37 UTC by vevek

Closes #166

2021-03-24 18:38 UTC, vevek commented
Ready for review, thanks!

2021-03-25 08:24 UTC, samuelfangjw requested changes

2021-03-25 08:24 UTC, samuelfangjw commented on src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
> +        // different person -> returns false
typo here

2021-03-25 08:27 UTC, vevek commented on src/test/java/seedu/address/logic/commands/DeleteEventCommandTest.java
> +        // different person -> returns false
Nice. fixed!

2021-03-25 08:42 UTC, samuelfangjw approved these changes, later dismissed

2021-03-25 08:45 UTC, samuelfangjw approved these changes
lgtm

2021-03-25 08:56 UTC, merged