Update Use cases and Manual testing examples
AY2021S2-CS2103T-T11-2/tp pull request #358
Opened 2021-04-11 17:33 UTC by lirc572

Preview of use cases: <https://lirc572.github.io/tp/DeveloperGuide.html#use-cases>

2021-04-11 18:12 UTC, samuelfangjw submitted a review, later dismissed
not related to this  PR, but notice this sentence at the start of UC section

`(For all use cases below, the System is CoLAB and the Actor is the user, unless specified otherwise)`

Would it be better if the brackets were removed?

2021-04-11 18:51 UTC, vevek commented on docs/DeveloperGuide.md
> +* 2a. The list of todos is empty.
list of todos/deadline

2021-04-11 18:53 UTC, vevek requested changes
Nice! only that minor change

2021-04-12 04:22 UTC, vevek approved these changes
LGTM!

2021-04-12 04:24 UTC, merged