Add tests utility
AY2021S2-CS2103T-T11-2/tp pull request #93
Opened 2021-03-13 15:07 UTC by samuelfangjw

Add test utility to make it easier to add tests in the future.

2021-03-13 20:26 UTC, Eriksen2411 requested changes

2021-03-13 20:26 UTC, Eriksen2411 commented on src/main/java/seedu/address/model/project/DeadlineList.java
> +     * @return A copy of this {@code DeadlineList}
hey samuel I'm not sure about this, but as I see it from javadoc format of other methods, there should be a blank line between description of method and parameter, return, throw

2021-03-13 20:26 UTC, Eriksen2411 commented on src/main/java/seedu/address/model/task/repeatable/Event.java
> -                && otherEvent.getIsDone().equals(getIsDone());
I think this is a complicated boolean expression as code quality says about it. You can choose to keep that or separate them 1 by 1

2021-03-13 20:26 UTC, Eriksen2411 commented on src/test/java/seedu/address/testutil/ProjectBuilder.java
> +    public Project build() {
should this have a javadoc

2021-03-13 20:26 UTC, Eriksen2411 commented on src/test/java/seedu/address/testutil/ProjectsFolderBuilder.java
> +    public ProjectsFolderBuilder() {
this 2 method missing javadoc also, as for other builder, you put javadoc for constructor also

2021-03-13 20:26 UTC, Eriksen2411 commented on src/test/java/seedu/address/testutil/TodoBuilder.java
> +}
Ahhh, OK I think that is all I can spot for now. For cases to test, I cannot think of other cases to add.

2021-03-14 05:21 UTC, vevek approved these changes
LGTM!

2021-03-14 08:48 UTC, Eriksen2411 approved these changes
LGTM

2021-03-14 08:49 UTC, merged